"""add_execution_tables

Revision ID: 36ce3cc51895
Revises: b6e82e8b6878
Create Date: 2026-05-19 22:58:19.800156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ce3cc51895'
down_revision: Union[str, Sequence[str], None] = 'b6e82e8b6878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'case_version', name='uq_automation_case_version')
    )
    with op.batch_alter_table('automation_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_codes_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('case_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('automation_code_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['automation_code_id'], ['automation_codes.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_records.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_results_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_results_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('execution_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_result_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_result_id'], ['case_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_media_case_result_id'), ['case_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_media_case_result_id'))

    op.drop_table('execution_media')
    with op.batch_alter_table('case_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_results_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_case_results_execution_id'))

    op.drop_table('case_results')
    with op.batch_alter_table('automation_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_codes_test_case_id'))

    op.drop_table('automation_codes')
    # ### end Alembic commands ###
