"""add_test_case_tables

Revision ID: 50fdd0a702a9
Revises: 
Create Date: 2026-05-19 22:13:15.698558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fdd0a702a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('precondition_steps', sa.Text(), nullable=True),
    sa.Column('main_steps', sa.Text(), nullable=False),
    sa.Column('system_category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_cases_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_system_category'), ['system_category'], unique=False)

    op.create_table('media_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_value', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('import_source_id', sa.String(length=36), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_data')
    op.drop_table('media_attachments')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_system_category'))
        batch_op.drop_index(batch_op.f('ix_test_cases_name'))
        batch_op.drop_index(batch_op.f('ix_test_cases_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_test_cases_case_number'))

    op.drop_table('test_cases')
    # ### end Alembic commands ###
