"""add_chat_message_type_field

Revision ID: 6e42bf6077d7
Revises: aad5bade138e
Create Date: 2026-07-04 21:16:48.463241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e42bf6077d7'
down_revision: Union[str, Sequence[str], None] = 'aad5bade138e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('CHAT', 'TRIAL_RUN_RESULT', name='chatmessagetype'), nullable=False, server_default='CHAT'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_chat_messages', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
