"""add_checklist_and_execution_tables

Revision ID: ab44757a64ad
Revises: bfff52e9d8bd
Create Date: 2026-05-19 22:36:47.561009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab44757a64ad'
down_revision: Union[str, Sequence[str], None] = 'bfff52e9d8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=True),
    sa.Column('source_case_id', sa.String(length=36), nullable=True),
    sa.Column('execution_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parallel_mode', sa.Boolean(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(checklist_id IS NOT NULL AND source_case_id IS NULL) OR (checklist_id IS NULL AND source_case_id IS NOT NULL)', name='ck_execution_has_one_source'),
    sa.ForeignKeyConstraint(['checklist_id'], ['test_checklists.id'], ),
    sa.ForeignKeyConstraint(['source_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_records_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_records_source_case_id'), ['source_case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_records_source_case_id'))
        batch_op.drop_index(batch_op.f('ix_execution_records_checklist_id'))

    op.drop_table('execution_records')
    # ### end Alembic commands ###
